FROM golang:1.26-alpine

WORKDIR /app

# Install git, build tools, and air for hot-reloading
RUN apk add --no-cache git build-base just

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# Disable git version stamping by Go as .git is in .dockerignore, so it will fail always
RUN go env -w GOFLAGS=-buildvcs=false

EXPOSE 8080

CMD ["just", "dev"]