import io
import json
import argparse
from pathlib import Path

import requests
from PIL import Image


def download_image(url: str) -> Image.Image:
    """Download an image and return it as a PIL image."""
    response = requests.get(url, timeout=30)
    response.raise_for_status()

    return Image.open(io.BytesIO(response.content)).convert("RGBA")


def export_patches(result: dict, output_dir: str):
    url = result["url"]
    patches = result["patches"]

    print(f"Downloading: {url}")

    image = download_image(url)

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    print(f"Original image: {image.width}x{image.height}")
    print(f"Patches: {len(patches)}")
    print(f"Output folder: {output_path}")

    for index, patch in enumerate(patches):
        x = patch["x"]
        y = patch["y"]
        size = patch["size"]
        score = patch["score"]

        # Crop the original pixels.
        crop = image.crop((
            x,
            y,
            x + size,
            y + size,
        ))

        filename = (
            f"{index:04d}"
            f"_score-{score:.4f}"
            f"_x-{x}"
            f"_y-{y}.png"
        )

        crop.save(output_path / filename)

    print(f"Done. Saved {len(patches)} crops.")


def main():
    parser = argparse.ArgumentParser(
        description="Export patches from an image-patch results JSON."
    )

    parser.add_argument(
        "--results",
        default="patches.json",
        help="JSON file generated by create_blocks.py",
    )

    parser.add_argument(
        "--index",
        type=int,
        required=True,
        help="Index of the image result to export.",
    )

    parser.add_argument(
        "--output",
        default="patches",
        help="Folder to save cropped images.",
    )

    args = parser.parse_args()

    # Read the results generated by the first script.
    with open(args.results, "r", encoding="utf-8") as f:
        results = json.load(f)

    if not isinstance(results, list):
        raise ValueError(
            "Expected the results JSON to contain a list."
        )

    if args.index < 0 or args.index >= len(results):
        raise IndexError(
            f"Index {args.index} is out of range. "
            f"There are {len(results)} results."
        )

    result = results[args.index]

    # Handle an image that failed during the first script.
    if "error" in result:
        raise RuntimeError(
            f"This image failed during processing: {result['error']}"
        )

    export_patches(
        result=result,
        output_dir=args.output,
    )


if __name__ == "__main__":
    main()
